---
abstract: unknown
author:
  - '扶凯 <iakuf@163.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-MultiDownload
no_index:
  directory:
    - t
    - inc
requires:
  AE: 0
  AnyEvent::HTTP: 2.21
  AnyEvent::Socket: 0
  AnyEvent::Util: 0
  EV: 0
  File::Basename: 0
  File::Copy: 0
  File::Temp: 0
  List::Util: 0
  Moo: 0
  Test::More: 0
resources:
  repository: https://github.com/iakuf/anyevent-multidownload
version: 1.04
